// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4uFpO6PCXp1K7mCMXlwHkvALe_YNkG9Q',
    appId: '1:944223929152:web:582172a6af2dda3b91b0a5',
    messagingSenderId: '944223929152',
    projectId: 'ecommerce-c2583',
    authDomain: 'ecommerce-c2583.firebaseapp.com',
    storageBucket: 'ecommerce-c2583.firebasestorage.app',
    measurementId: 'G-0F5NM8HHKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRiCcy0U9vUWHKK0reu7dHqDz7b0EC_gI',
    appId: '1:944223929152:android:b4a8d2381f4a2d7591b0a5',
    messagingSenderId: '944223929152',
    projectId: 'ecommerce-c2583',
    storageBucket: 'ecommerce-c2583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9S1PUFY2FQ-b2aTeRLgAdDXmbAMWhbok',
    appId: '1:944223929152:ios:a5035fcfd62c4d9b91b0a5',
    messagingSenderId: '944223929152',
    projectId: 'ecommerce-c2583',
    storageBucket: 'ecommerce-c2583.firebasestorage.app',
    iosBundleId: 'com.example.fastProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9S1PUFY2FQ-b2aTeRLgAdDXmbAMWhbok',
    appId: '1:944223929152:ios:a5035fcfd62c4d9b91b0a5',
    messagingSenderId: '944223929152',
    projectId: 'ecommerce-c2583',
    storageBucket: 'ecommerce-c2583.firebasestorage.app',
    iosBundleId: 'com.example.fastProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4uFpO6PCXp1K7mCMXlwHkvALe_YNkG9Q',
    appId: '1:944223929152:web:bce2eadbbacb3bd791b0a5',
    messagingSenderId: '944223929152',
    projectId: 'ecommerce-c2583',
    authDomain: 'ecommerce-c2583.firebaseapp.com',
    storageBucket: 'ecommerce-c2583.firebasestorage.app',
    measurementId: 'G-F9DJT4VD9Y',
  );
}
